name = "do-playground-worker"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for KVStore Durable Object example
[[ kv_namespaces ]]
binding = "KV_CACHE"
id = "09b26554bff341f4b797eb4dbec05411"

[[ durable_objects.bindings ]]
name = "COUNTER"
class_name = "Counter"
script_name = "do-playground-worker"

[[ durable_objects.bindings ]]
name = "CHAT_ROOM"
class_name = "ChatRoom"
script_name = "do-playground-worker"

[[ durable_objects.bindings ]]
name = "BATCHER"
class_name = "Batcher"
script_name = "do-playground-worker"

[[ durable_objects.bindings ]]
name = "RATE_LIMITER"
class_name = "RateLimiter"
script_name = "do-playground-worker"

[[ durable_objects.bindings ]]
name = "LOCATION"
class_name = "Location"
script_name = "do-playground-worker"

[[ durable_objects.bindings ]]
name = "SESSION"
class_name = "Session"
script_name = "do-playground-worker"

[[ durable_objects.bindings ]]
name = "STREAMER"
class_name = "Streamer"
script_name = "do-playground-worker"

[[ durable_objects.bindings ]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"
script_name = "do-playground-worker"

[[ durable_objects.bindings ]]
name = "KV_STORE"
class_name = "KVStore"
script_name = "do-playground-worker"

[[ durable_objects.bindings ]]
name = "LATENCY_TESTER"
class_name = "LatencyTester"
script_name = "do-playground-worker"

[[ migrations ]]
tag = "v1"
new_sqlite_classes = ["Counter", "ChatRoom"]

[[ migrations ]]
tag = "v2"
new_sqlite_classes = ["Batcher"]

[[ migrations ]]
tag = "v3"
new_sqlite_classes = ["RateLimiter"]

[[ migrations ]]
tag = "v4"
new_sqlite_classes = ["Location"]

[[ migrations ]]
tag = "v5"
new_sqlite_classes = ["Session"]

[[ migrations ]]
tag = "v6"
new_sqlite_classes = ["Streamer"]

[[ migrations ]]
tag = "v7"
new_sqlite_classes = ["MyDurableObject"]

[[ migrations ]]
tag = "v8"
new_sqlite_classes = ["KVStore"]

[[ migrations ]]
tag = "v9"
new_sqlite_classes = ["LatencyTester"]

